version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 80:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: RKtNCjnweZ7u9KwI
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:    
      - ./:/mnt/host

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RKtNCjnweZ7u9KwI
      MYSQL_DATABASE: redmine
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci